training:
  model_name: 'textcnn'
  learning_rate: 0.8
  embedding_dim: 100
preprocessing:
  input_convertor: 'nn_vectorization'
  embedding_dim: 100
predict:
  output_path: ./data/textcnn_submission.csv